---
- name: Disable swap (if configured).
  command: swapoff -a
  when:
    - ansible_facts.memory_mb['swap']['total'] > 0
    - not swap_test_mode
  tags: ['skip_ansible_lint']

- name: Ensure swap file doesn't exist (if configured).
  file:
    path: "{{ swap_file_path }}"
    state: absent
