---
- name: Disable swap (if configured).
  command: "swapoff {{ swap_file_path }}"
  args:
    removes: "{{ swap_file_path }}"
  when: ansible_memory_mb['swap']['total'] > 0
  tags: ['skip_ansible_lint']

- name: Ensure swap file doesn't exist (if configured).
  file:
    path: "{{ swap_file_path }}"
    state: absent
